version: "3.8"
services:
  autocarml:
    build:
      context: .
      dockerfile: autocarml/dockerfiles/kedro/Dockerfile
      args:
        - BASE_IMAGE=amd64/python:3.8-buster
        - KEDRO_UID=999
        - KEDRO_GID=0
    ports:
      - "8888:8888"
    environment:
      - PYTHONPATH=/home/kedro_docker
    volumes:
      - data_volume:/data
    working_dir: /home/kedro_docker
    command: ["kedro", "run"]
  autocar_api:
    build:
      context: .
      dockerfile: autocarml/dockerfiles/api/Dockerfile
      args:
        - BASE_IMAGE=python:3.8-slim
    ports:
      - "5000:80"
    volumes:
      - data_volume:/data
    working_dir: /code
    command: ["uvicorn", "app.fastApi:app", "--host", "0.0.0.0", "--port", "80"]
volumes:
  data_volume: