version: "3.8"
services:
  autocarml:
    build:
      context: .
      dockerfile: ./autocarml/Dockerfile
      args:
        - BASE_IMAGE=amd64/python:3.9-buster
        - KEDRO_UID=999
        - KEDRO_GID=0
    ports:
      - 8888:8888
    environment:
      - PYTHONPATH=/home/kedro_docker
    volumes:
      - data_volume:/home/kedro_docker
    working_dir: /home/kedro_docker
    command: ["kedro", "run"]
  autocar_api:
    build:
      context: .
      dockerfile: ./autocar_API/Dockerfile
      args:
        - BASE_IMAGE=python:3.9-slim
    ports:
      - 80:80
    volumes:
      - data_volume:/code
    working_dir: /code
    command: ["uvicorn", "app.fastApi:app", "--host", "0.0.0.0", "--port", "80"]
volumes:
  data_volume: