wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1670268426.663372
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.5
      5: 0.13.5
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 128
classes:
  desc: null
  value: 10
dataset:
  desc: null
  value: MNIST
epochs:
  desc: null
  value: 5
kernels:
  desc: null
  value:
  - 16
  - 32
learning_rate:
  desc: null
  value: 0.005
